Description: Raiinmaker Service

Parameters:
  Stage:
    Type: String
    Default: "staging"

  EnableCFDomains:
    Type: String
    Default: "true"

  hostedZoneId:
    Type: "String"
    Default: "Z0717136XJL2MFL4R79M"

  sslCertificateArn:
    Type: "String"
    Description: "Arn for the SSL cert to attach, defaults to *.api.raiinmaker.com cert"
    Default: "arn:aws:acm:us-east-1:527252880472:certificate/ef2bae53-4c35-482b-806c-86d6178ef73d"

Conditions:
  isProd:
    Fn::Equals:
      - Ref: Stage
      - "production"
  EnableDomains:
    Fn::Equals:
      - Ref: EnableCFDomains
      - "true"


Resources:
    raiinmakerRoute53:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: Z0717136XJL2MFL4R79M
        Name:
          Fn::If:
            - isProd
            - server.api.raiinmaker.com
            - Fn::Join:
                - ''
                - - server-
                  - Ref: Stage
                  - .api.raiinmaker.com
        Type: CNAME
        ResourceRecords:
          - Fn::If:
              - isProd
              - "f14185dd-raiinmaker-raiinm-4ef8-1562188963.us-west-1.elb.amazonaws.com"
              - "eadf2937-raiinmaker-raiinm-4ef8-1121023472.us-west-1.elb.amazonaws.com"
        TTL: "300"

    BucketRoute53Configurations:
      Condition: EnableDomains
      Type: AWS::Route53::RecordSet
      Properties:
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName:
            Fn::GetAtt:
              - BucketCloudFrontDistribution
              - DomainName
        HostedZoneId: Z0717136XJL2MFL4R79M
        Name:
          Fn::If:
            - isProd
            - "raiinmaker-media.api.raiinmaker.com"
            - Fn::Join:
              - ""
              - - raiinmaker-media-
                - Ref: Stage
                - .api.raiinmaker.com
        Type: A


    raiinmakerMediaOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: S3 Raiinmaker Media Origin Access Identity

    BucketCloudFrontDistribution:
      Condition: EnableDomains
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - Fn::If:
              - isProd
              - "raiinmaker-media.api.raiinmaker.com"
              - Fn::Join:
                  - ""
                  - - raiinmaker-media-
                    - Ref: Stage
                    - .api.raiinmaker.com
          Enabled: true
          Origins:
            - DomainName:
                Fn::GetAtt:
                  - raiinmakerS3Bucket
                  - DomainName
              Id: origin
              S3OriginConfig:
                OriginAccessIdentity:
                  Fn::Join:
                    - '/'
                    - - origin-access-identity/cloudfront
                      - Ref: raiinmakerMediaOriginAccessIdentity
          DefaultCacheBehavior:
            TargetOriginId: origin
            DefaultTTL: 1440 # 1 day in minutes before cache clears
            ForwardedValues:
              QueryString: false
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            SmoothStreaming: true
          ViewerCertificate:
            AcmCertificateArn:
              Ref: sslCertificateArn
            SslSupportMethod: sni-only

    raiinmakerS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName:
          Fn::Join:
            - ''
            - - rm-raiinmaker-
              - Ref: Stage

    raiinmakerKycKmsKey:
      Type: AWS::KMS::Key
      Properties:
        Description: Used for managing kyc
        Enabled: true
        PendingWindowInDays: 7
        KeyPolicy:
          Version: '2012-10-17'
          Statement:
            - Sid: Allow raiinmaker service role permission to use key
              Effect: Allow
              Action: ["kms:*"]
              Principal:
                AWS: '*'
              Resource: '*'
        Tags:
          - Key: Name
            Value:
              Fn::Join:
                - ''
                - - rm-raiinmaker-kyc-
                  - Ref: Stage

    raiinmakerKycBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                KMSMasterKeyID:
                  Ref: raiinmakerKycKmsKey
                SSEAlgorithm: aws:kms
        BucketName:
          Fn::Join:
            - ''
            - - rm-raiinmaker-kyc-
              - Ref: Stage

    raiinmakerMediaBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: raiinmakerS3Bucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - "s3:GetObject"
              Principal:
                CanonicalUser:
                  Fn::GetAtt: [raiinmakerMediaOriginAccessIdentity, S3CanonicalUserId]
              Resource:
                Fn::Join:
                  - "/"
                  - - Fn::GetAtt: [raiinmakerS3Bucket, Arn]
                    - "*"

    raiinmakerServiceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                AWS:
                  Fn::If:
                    - isProd
                    - arn:aws:iam::527252880472:role/eksctl-raiinmaker-production-cluster-ServiceRole-1BU2N2RS88OHF
                    - arn:aws:iam::527252880472:role/eksctl-raiinmaker-staging-cluster-ServiceRole-Q18O77ELY64T
        RoleName:
          Fn::Join:
            - "-"
            - - "raiinmaker"
              - Ref: Stage

    raiinmakerServicePolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName:
          Fn::Join:
            - "-"
            - - raiinmaker-service-policy
              - Ref: Stage
        Roles:
          - Ref: raiinmakerServiceRole
        PolicyDocument:
          Version : "2012-10-17"
          Statement:
            - Effect: Allow
              Action: ["kms:*"]
              Resource:
                - Fn::GetAtt: [raiinmakerKycKmsKey, Arn]
            - Effect: Allow
              Action:
                - s3:*
              Resource:
                - Fn::GetAtt: [raiinmakerS3Bucket, Arn]
                - Fn::Join:
                  - ''
                  - - Fn::GetAtt: [raiinmakerS3Bucket, Arn]
                    - '/*'
                - Fn::GetAtt: [raiinmakerKycBucket, Arn]
                - Fn::Join:
                  - ''
                  - - Fn::GetAtt: [raiinmakerKycBucket, Arn]
                    - '/*'
            - Effect: Allow
              Action:
                - 'ses:*'
              Resource: '*'
