# Default values for raiinmaker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
    repository: 527252880472.dkr.ecr.us-west-1.amazonaws.com/raiinmaker
    tag: staging-0.0.1
    pullPolicy: Always

iamRole: arn:aws:iam::527252880472:role/raiinmaker-staging

securityContext:
    runAsNonRoot: true
    runAsUser: 1000

service:
    type: NodePort
    port: 8080

ingress:
    enabled: true
    host: server-staging.api.raiinmaker.com

cron:
    frequency:
        social: "0 */3 * * *" # At minute 0 every 3 hours
        daily: "0 0 * * *" # At minute 0 every day
        # coiinWatcher: "*/5 * * * *" # At every 5 minutes
        qualityScore: "0 */3 * * *" # At minute 0 every hour
        campaignAudit: "0 * * * *" # At every hour
        fixTransfer: "0 */6 * * *" # At every 6 hour
        marketData: "*/15 * * * *" # At every 15 minutes

# up server replica count
replicaCount: 2
server:
    resources:
        limits:
            cpu: 500m
            memory: 3Gi
        requests:
            cpu: 500m
            memory: 3Gi

aws:
    secret_key:

data:
    IAM_ROLE: arn:aws:iam::527252880472:role/raiinmaker-staging
    environment:
        NODE_ENV: "staging"
        BUCKET_NAME: "rm-raiinmaker-staging"
        KYC_BUCKET_NAME: "rm-raiinmaker-kyc-staging"
        RM_SECRETS: "rm-secrets-staging"
        TATUM_WALLETS: "tatum-wallets-stage"
        RATE_LIMIT_MAX: "50"
        RATE_LIMIT_WINDOW: "1m"
        REWARD_REDEMPTION_EMAIL_RECIPIENT: "ray@raiinmaker.com"
        TATUM_RETRY_DELAY: "1000"
        TATUM_RETRIES: "5"
        ETHEREUM_DEPOSIT_ADDRESS: "0x275EE6238D103fDBE49d4cF6358575aA914F8654"
        RAIINMAKER_DEV_TOKEN: "0dfdd4-e5a5a3-c657fc-36415b-116af1"
        MIN_WITHDRAW_LIMIT: "100"
        COIIN_VALUE: "0.2"
        FEE_RATE: "0.1"
        FIREBASE_API_KEY: "AIzaSyAAXv6aKS3xdrnTLf5hVVJgW60h26vFJok"
        FIREBASE_ADMIN_API_KEY: "AIzaSyAVSYceauLhAEQMe9CZIYXjksPkQP6KZCM"
        SENTRY_DSN: "https://ba0ee0b07cad495bba9d8734bd37cf34@o1155640.ingest.sentry.io/6236187"
        PG_HOST_READER: "staging-database.cluster-ro-cuqkwt1n17k6.us-west-1.rds.amazonaws.com"
        SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
        ORG_BUCKET_NAME: "rm-org-staging"

postgresql:
    existingSecret: "raiinmaker"
    host: "staging-database.cluster-custom-cuqkwt1n17k6.us-west-1.rds.amazonaws.com"
    persistence:
        storageClass: gp2
        accessMode: ReadWriteOnce
    replication:
        enabled: true
        synchronousCommit: "on"
        numSynchronousReplicas: 1
        slaveReplicas: 1

pg-bak:
    service: raiinmaker
    stage: staging
    existingSecret: "raiinmaker"
    postgresHost: raiinmaker-api-postgresql-read
    s3Bucket: rm-postgres-backups
    iamRole: arn:aws:iam::527252880472:role/PostgresBackupRole
    image:
        repository: 527252880472.dkr.ecr.us-west-1.amazonaws.com/pg_backup
        tag: "1.0.3"

redis:
    image:
        repository: redis
        tag: 5.0.7-alpine
    resources:
        limits:
            cpu: 1
            memory: 200Mi
        requests:
            cpu: 15m
            memory: 200Mi
