image:
    pullPolicy: IfNotPresent

iamRole: arn:aws:iam::527252880472:role/raiinmaker-production

pg-bak:
    stage: production

ingress:
    host: server.api.raiinmaker.com

data:
    IAM_ROLE: arn:aws:iam::527252880472:role/raiinmaker-production
    environment:
        NODE_ENV: "production"
        BUCKET_NAME: "rm-raiinmaker-production"
        KYC_BUCKET_NAME: "rm-raiinmaker-kyc-production"
        RM_SECRETS: "rm-secrets"
        RATE_LIMIT_MAX: "3"
        RATE_LIMIT_WINDOW: "1m"
        REWARD_REDEMPTION_EMAIL_RECIPIENT: jonel@raiinmaker.com
        TATUM_RETRY_DELAY: 1000
        TATUM_RETRIES: 5
        ETHEREUM_DEPOSIT_ADDRESS: 0x9f6fE7cF8CCC66477c9f7049F22FbbE35234274D
